### ISSUE TITLE
NoHappensBefore 中stop的修改 为什么没有被子线程看到

### ISSUE THREAD

**Issue by chy996633** [chanjarster/java-concurrency-learn#1]
我理解他们的确没有先行关系，但是当主线程休眠完后，stop变量的值的确应该被修改了，然后子线程就应该要看到了？

**Comment by chanjarster** [comment]
虽然本项目的文章并未公开过，但是既然你问我，我就用我仅有的一些知识尝试回答你，不要把我的回答当作权威答案，多线程这块我也不熟。

从硬件角度来看，CPU不是直接从内存（准确来说是称为主存，Main Memory）读取数据的，而是先由CPU  Cache从Main Memory加载，CPU再从Cache中读取的。CPU的Cache有好几层，你一定听说过CPU一级缓存、CPU二级缓存。

在多核（也就是多CPU）机器架构中，CPU之间的Cache是相互独立的，那么很明显的一个问题就出现了，两个CPU Cache的数据会产生不一致。

在硬件层面，CPU采用MESI协议来保证对同一份数据的两个独立CPU Cache的数据的一致性，但是到了JVM层面得通过Happens Before来保证。

问题来了，既然JVM是用C编写的，而C语言可以直接利用硬件的MESI来解决CPU Cache一致性的问题，为何JVM却得通过Happens Before来保证呢？

这个问题的答案我也不清楚，不过可以肯定的是，这个问题和内存模型（Memory Model）有关，而硬件的内存和JVM的内存模型是不一样的。你应该从这个角度去研究一下。有了答案的话记得告诉我一声。
